spring:
  # 数据源相关配置
  datasource:
    url: jdbc:mysql://localhost:3306/answer?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: xxxxxx
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  # 签名
  signature: XGKX_JZAB_MJJ
  # 过期时间  单位 s
  exp: 604800  # 7 * 60 * 60 * 24

server:
  port: 8080
  servlet:
    context-path: /api

file:
  excelPath: src\\main\\resources\\static\\模板.xlsx